### ISSUE TITLE
Nice mod!

### ISSUE THREAD

**Issue by joaoszaaa** [Stephen-C111/BattlePassPixelmon#1]
Can u add listeners to:

npc defeat

?

**Comment by Stephen-C111** [comment]
Should be simple enough. I'll probably increase the reward based off of the level / boss type of the trainer, similarly to how catching/defeating is calculated based off of level right now.

**Comment by Stephen-C111** [comment]
I released a bugfix update which also includes your requested feature. Check out 0.3.1. It will create a new config so if you did any modifications to the previous config you'll need to change those variables again.
