### ISSUE TITLE
Add more config

### ISSUE THREAD

**Issue by joaoszaaa** [Stephen-C111/BattlePassPixelmon#2]
I know this will probaly be hard, but can u add more config's to the mod?

Like:

1. Make a way to config the message that cames on bossbar (To make traductions to other languages etc)
2. Make a way to config rewards

**Comment by Stephen-C111** [comment]
Translations are a bit out of scope right now, and reward tweaking is a planned feature.

**Comment by Stephen-C111** [comment]
Configuration for both RewardPacks and random rewards are implemented as of 0.4.3.
The "Battle Pass" text on the boss bar is configurable from config\battlepasspixelmon-commonconfig-0.3.1.toml under the definition of "BossBarDefaultTitle". You will have to restart the server for it to take effect.

As I am not considering translations until all functionality is present, I will mark this closed for now.
