### ISSUE TITLE
Any chance for GUI?

### ISSUE THREAD

**Issue by aglarcz** [Stephen-C111/BattlePassPixelmon#3]
Any chance to include GUI? I know its quite a much of work but I am willing to donate for that feature.

**Comment by Stephen-C111** [comment]
I want to implement a GUI eventually but this is my first forge mod, so it'll take me some time to get familiar with Minecraft's weird server-side GUI system.
There's some planned features that are only going to be intuitively usable with a GUI, so it should happen eventually as time permits. On that topic, I've been debating whether to display the rank as part of the scoreboard system or a boss health bar. It would be feasible to make either optional, I suppose.

**Comment by Stephen-C111** [comment]
The bossbar displays your current rank progress at the top of the screen and the journal from /getjournal displays active bounties. As for the bounties you're working on, I was going to implement these via the scoreboard system, but it was unpleasant to look at and not pleasant to manage. /acceptedbounties works fine for this purpose, without having a constant wall of text covering your screen. 
For now, this is all I can do GUI-wise without requiring a client-side installation, and so I will close this issue now.
